services:
  db_pg_demo:
    image: postgres:15
    environment:
      POSTGRES_DB: db_animals
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data_animal.sql:/docker-entrypoint-initdb.d/data_animal.sql
    ports:
      - 5432:5432
